package entity.entities

enum class abonent_source_type { DB_LIST, API }
enum class abonent_state { INVALID_MSISDN, CHECKED, UNCHECKED }
enum class communication_status_type { DRAFT, ACTIVE, FINISHED, DELETED, STOPPED }
enum class result_code_type {NO_ERROR, AUTH_ERROR, ATTEMPT_TO_START_NO_DRAFT_COMMUNICATION,
    ATTEMPT_TO_START_COMMUNICATION_IN_THE_PAST, ATTEMPT_TO_STOP_NO_ACTIVE_COMMUNICATION, ATTEMPT_TO_TEST_ON_BUSY_NUMBER,
    ATTEMPT_TO_TEST_NO_DRAFT_COMMUNICATION, NO_ALLOW_API_ERROR, ATTEMPT_TO_SEND_API_NO_ACTIVE_COMMUNICATION,
    ATTEMPT_TO_SEND_API_NO_API_COMMUNICATION, ATTEMPT_TO_SEND_API_BAD_PARAMS, ATTEMPT_TO_SEND_INVALID_MSISDN,
    ATTEMPT_TO_START_WITH_INVALID_SCHEMA, STUB
}
